Mimic.copy(Transport)
Mimic.copy(KeyValueEx.RedisClient.Connection)
Mimic.copy(KeyValueEx.RedisClient.Main)
Mimic.copy(KeyValueEx.RedisClient.Parser)
ExUnit.start()
# Ecto.Adapters.SQL.Sandbox.mode(KeyValueEx.Repo, :manual)
